version: '3'
services:
  binaryxtools-telegrambot:
    build:
      context: ./
      dockerfile: Dockerfile
    container_name: binaryxtools-telegrambot
    restart: always
    environment:
      - MONGO_URL=mongodb://lynxrufus:atmylynxrufusserver@mongo:27017/
      - MONGO_DB_NAME=cryptoWarehouse
      - STAGE=PROD
      - TELEGRAM_TOKEN=${TELEGRAM_TOKEN}
    networks:
      -  crypto-warehouse_default
networks:
  crypto-warehouse_default:
    external: true
